### ISSUE TITLE
Ranking System/Feedback system.

### ISSUE THREAD

**Issue by aaronsantiago** [aaronsantiago/PayUp#3]
For our next round of prototyping we want to experiment with ranking players based on their input times.

One potential implementation is to lock the master when a correct input is received, and wait for all other players to input before continuing.

Additionally, this ties into another feature where we want players to be notified via their input chain whether or not they were the winner.

**Comment by ReluctantPirate** [comment]
Another component of this was the "pipe" system for Blinks adjacent to the shuffler.

Any piece adjacent to the shuffler only listens for and propagates signals on the face attached to the shuffler and that face's opposite. This creates a "pipe" that prevents information from spreading to other players branches.

**Comment by aaronsantiago** [comment]
See #2
